-- =============================================================================
-- ICT SERVICE REQUEST MANAGEMENT SYSTEM - SUPABASE POSTGRESQL SCHEMA
-- Course: Systems Analysis and Design (SAD)
-- Table: service_requests
-- =============================================================================

-- 1. Create the main service_requests table
CREATE TABLE IF NOT EXISTS service_requests ( 
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  
  requester_name TEXT NOT NULL, 
  department TEXT NOT NULL, 
  category TEXT NOT NULL, 
  description TEXT NOT NULL, 
  priority TEXT NOT NULL, 
  status TEXT DEFAULT 'Pending', 
  created_at TIMESTAMPTZ DEFAULT NOW(), 
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE service_requests ENABLE ROW LEVEL SECURITY;

-- 3. Row Level Security Policies
-- Policy 1: Allow public & authenticated users to view requests
DROP POLICY IF EXISTS "Authenticated users can view requests" ON service_requests;
DROP POLICY IF EXISTS "Public users can view requests" ON service_requests;
CREATE POLICY "Public users can view requests" ON service_requests 
  FOR SELECT 
  TO public 
  USING (true);

-- Policy 2: Allow authenticated & anon users to insert requests
DROP POLICY IF EXISTS "Authenticated users can insert requests" ON service_requests;
DROP POLICY IF EXISTS "Public users can insert requests" ON service_requests;
CREATE POLICY "Public users can insert requests" ON service_requests 
  FOR INSERT 
  TO public 
  WITH CHECK (true);

-- Policy 3: Allow users to update requests
DROP POLICY IF EXISTS "Authenticated users can update requests" ON service_requests;
DROP POLICY IF EXISTS "Public users can update requests" ON service_requests;
CREATE POLICY "Public users can update requests" ON service_requests 
  FOR UPDATE
  TO public 
  USING (true);

-- Policy 4: Allow users to delete requests
DROP POLICY IF EXISTS "Authenticated users can delete requests" ON service_requests;
DROP POLICY IF EXISTS "Public users can delete requests" ON service_requests;
CREATE POLICY "Public users can delete requests" ON service_requests 
  FOR DELETE 
  TO public 
  USING (true);

-- =============================================================================
-- Initial Sample Seed Data (Executes automatically when running schema in Supabase)
-- =============================================================================
INSERT INTO service_requests (requester_name, department, category, description, priority, status, created_at)
VALUES 
  ('Juan Dela Cruz', 'Registrar', 'Internet/network problem', 'Computer cannot connect to university Wi-Fi in Admin Bldg.', 'High', 'Pending', NOW() - INTERVAL '2 hours'),
  ('Maria Clara', 'Accounting', 'Printer problem', 'Paper jam issue and offline status on HP LaserJet 1020.', 'Medium', 'In Progress', NOW() - INTERVAL '1 day'),
  ('Crisostomo Ibarra', 'College of Computer Studies', 'Software installation', 'Requesting installation of SPSS 28 and VS Code for lab instruction.', 'Low', 'Completed', NOW() - INTERVAL '3 days'),
  ('Ana Santos', 'Human Resources', 'Account/access concern', 'Forgot password for faculty portal login.', 'High', 'Pending', NOW() - INTERVAL '30 minutes'),
  ('Pedro Penduko', 'Library Services', 'Computer repair', 'Desktop computer auto shutdowns after 10 minutes of usage.', 'High', 'In Progress', NOW() - INTERVAL '5 hours');

